name: Build and Push Docker Image

on:
  workflow_dispatch:

concurrency:
  group: docker-publish
  cancel-in-progress: true

env:
  CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $CONTAINER_REGISTRY/${{ secrets.ACR_USERNAME }}/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $CONTAINER_REGISTRY/${{ secrets.ACR_USERNAME }}/$IMAGE_NAME:latest