name: Exploring Variables and Secrets

on:
  push:

# Global environment variables accessible throughout the workflow
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    # Job-specific environment variables (override global if needed)
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ env.DOCKER_PASSWORD }}" | docker login ${{ env.CONTAINER_REGISTRY }} \
            --username ${{ env.DOCKER_USERNAME }} \
            --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest