name: workflow_1
on: push
jobs:
  omar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: welcome
        run: echo "Welcome to Omar's workflow!"
      - name: cow sa
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cowsay  
          cowsay -f dragon "dragon is here!" >> dragon.txt
          cat dragon.txt
      - name: show read me
        run: |
          ls -ltrah
          cat README.md